# Generated by Django 5.1.4 on 2024-12-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nightuser',
            managers=[
            ],
        ),
    ]
