# Generated by Django 5.1.4 on 2025-01-04 11:15

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=30, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحاتـ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('material', models.CharField(default='برنزی', max_length=25, verbose_name='حنس')),
                ('inventory', models.IntegerField(default=0, verbose_name='تعداد موجودی')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='ورن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تولید شده در')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('status', models.BooleanField(default=True, verbose_name='وضیعت محصول')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مجصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[500, 500], upload_to='images/', verbose_name='عکس ها')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شد در')),
                ('is_main', models.BooleanField(default=False, verbose_name='عکس اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='عکس محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس های محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='اضافه شده در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='محصولات مورد علاقه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ویزگی')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feather_name', to='store.product', verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatherValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('feather_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feather_value', to='store.productfeaturename', verbose_name='نام ویزگی')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='اسلاگ')),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='store.product', verbose_name='محصول')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'slug'], name='store_categ_name_f50271_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='store_categ_parent__e56892_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='store_produ_id_2abda1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created', 'updated'], name='store_produ_created_ac8881_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_6683b7_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='store_image_created_e9694d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
