# Generated by Django 5.1.4 on 2025-01-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'محصوب', 'verbose_name_plural': 'محبوب ها'},
        ),
        migrations.AlterModelOptions(
            name='productfeathervalue',
            options={'verbose_name': 'مقدار ویزگی', 'verbose_name_plural': 'مقدار ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='productfeaturename',
            options={'verbose_name': 'ویزگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterField(
            model_name='productfeaturename',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feather_name', to='store.product', verbose_name='نام محصول'),
        ),
    ]
