# Generated by Django 5.1.4 on 2025-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default='برنجی', max_length=25, verbose_name='حنس'),
        ),
    ]
