# Generated by Django 5.1.4 on 2025-01-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturename',
            name='product',
        ),
        migrations.AddField(
            model_name='productfeathervalue',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product', verbose_name='نام محصول'),
            preserve_default=False,
        ),
    ]
