# Generated by Django 5.1.4 on 2025-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productfeaturename_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='night', max_length=25, verbose_name='برند'),
        ),
    ]
