# Generated by Django 5.1.4 on 2025-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن'),
        ),
    ]
