# Generated by Django 5.1.4 on 2025-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_copen_usercopenusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copen',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
    ]
