# Generated by Django 5.1.4 on 2025-01-21 09:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_copen_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[1920, 1080], upload_to='images/', verbose_name='عکس ها'),
        ),
    ]
