# Generated by Django 5.1.4 on 2025-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_category_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=55, verbose_name='توضیح مختصر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیر فعال')], default='inactive', max_length=25, verbose_name='وضیعت')),
                ('position', models.CharField(choices=[('top', 'بالا'), ('middle', 'وسط'), ('button', 'پایین')], default='top', max_length=25, verbose_name='مکان بنر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='store_banne_status_ac2204_idx'), models.Index(fields=['position'], name='store_banne_positio_abf99e_idx')],
            },
        ),
    ]
