# Generated by Django 5.1.4 on 2025-01-21 12:14

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان بنر')),
                ('short_description', models.CharField(blank=True, max_length=55, null=True, verbose_name='توضیحات مختصر بنر')),
                ('file', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[1920, 1080], upload_to='images/', verbose_name='')),
            ],
            options={
                'verbose_name': 'تصویر بنر',
                'verbose_name_plural': 'تصویر های بنر',
            },
        ),
    ]
