# Generated by Django 5.1.4 on 2025-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_bannerimage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default=0, max_length=55, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
