# Generated by Django 5.1.4 on 2025-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضیعت'),
        ),
    ]
