# Generated by Django 5.1.4 on 2025-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_banner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('short_description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='store.product')),
            ],
        ),
    ]
