# Generated by Django 5.1.4 on 2025-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_sliderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderproduct',
            name='location',
            field=models.CharField(choices=[('top', 'بالا'), ('middle', 'وسط'), ('button', 'پایین')], default='button', max_length=20),
        ),
    ]
