# Generated by Django 5.1.4 on 2025-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='اسلاگ'),
        ),
    ]
