# Generated by Django 5.1.4 on 2025-01-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_email_blogcomment_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='last_name',
        ),
    ]
