# Generated by Django 5.1.4 on 2025-01-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
