# Generated by Django 5.1.4 on 2025-01-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_address_city_alter_address_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.CharField(default=0, max_length=125),
            preserve_default=False,
        ),
    ]
