# Generated by Django 5.1.4 on 2025-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_address_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='note',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
